// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress(
    "NAME_SHADOWING",
    "FunctionName",
    "LocalVariableName",
    "ParameterName",
    "PropertyName",
    "SameReturnValue",
)

package com.tabslify.remote.uniffi.ironrdp_bridge

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_ironrdp_bridge_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): ByValue {
            val buf = ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: ByValue) = uniffiRustCall { status ->
            UniffiLib.ffi_ironrdp_bridge_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): ByValue {
            val callStatus = ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    val status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}



// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ironrdp_bridge"
}

// Define FFI callback types

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "ironrdp_bridge"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }

    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_diagnose(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_disconnect(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_frame_count(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_key_down(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_key_up(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_last_error(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_button(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_move(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_scroll(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_state(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_surface_size(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_take_frame(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_method_rdpsession_type_unicode(
    ): Int
    external fun uniffi_ironrdp_bridge_checksum_constructor_rdpsession_start(
    ): Int
    external fun ffi_ironrdp_bridge_uniffi_contract_version(
    ): Int


}

internal object UniffiLib {

    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }


    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "ironrdp_bridge"))

    }

    external fun uniffi_ironrdp_bridge_fn_clone_rdpsession(handle: Long,uniffi_out_err: UniffiRustCallStatus
    ): Long
    external fun uniffi_ironrdp_bridge_fn_free_rdpsession(handle: Long,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_constructor_rdpsession_start(options: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus
    ): Long
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_diagnose(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_disconnect(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_frame_count(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): Long
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_key_down(ptr: Long,scancode: Int,extended: Byte,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_key_up(ptr: Long,scancode: Int,extended: Byte,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_last_error(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_button(ptr: Long,button: RustBuffer.ByValue,pressed: Byte,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_move(ptr: Long,x: Short,y: Short,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_scroll(ptr: Long,horizontal: Short,vertical: Short,uniffi_out_err: UniffiRustCallStatus
    )
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_state(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_surface_size(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_take_frame(ptr: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun uniffi_ironrdp_bridge_fn_method_rdpsession_type_unicode(ptr: Long,code: Int,uniffi_out_err: UniffiRustCallStatus
    )
    external fun ffi_ironrdp_bridge_rustbuffer_alloc(size: Long,uniffi_out_err: UniffiRustCallStatus
    ): RustBuffer.ByValue
    external fun ffi_ironrdp_bridge_rustbuffer_free(buf: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus
    )


}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_ironrdp_bridge_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_diagnose() and 0xFFFF) != 63445) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_disconnect() and 0xFFFF) != 8261) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_frame_count() and 0xFFFF) != 28795) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_key_down() and 0xFFFF) != 31518) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_key_up() and 0xFFFF) != 44195) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_last_error() and 0xFFFF) != 9055) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_button() and 0xFFFF) != 11948) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_move() and 0xFFFF) != 61687) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_pointer_scroll() and 0xFFFF) != 12259) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_state() and 0xFFFF) != 8159) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_surface_size() and 0xFFFF) != 10925) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_take_frame() and 0xFFFF) != 39804) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_method_rdpsession_type_unicode() and 0xFFFF) != 44459) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_ironrdp_bridge_checksum_constructor_rdpsession_start() and 0xFFFF) != 52011) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (_: Throwable) {
            // swallow
        }
    }

/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (_: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner: java.lang.ref.Cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
object FfiConverterShort: FfiConverter<Short, Short> {
    override fun lift(value: Short): Short {
        return value
    }

    override fun read(buf: ByteBuffer): Short {
        return buf.getShort()
    }

    override fun lower(value: Short): Short {
        return value
    }

    override fun allocationSize(value: Short) = 2UL

    override fun write(value: Short, buf: ByteBuffer) {
        buf.putShort(value)
    }
}

/**
 * @suppress
 */
object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


interface RdpSessionInterface {

    fun diagnose(): String

    fun disconnect()

    fun frameCount(): ULong

    fun keyDown(scancode: Int, extended: Boolean)

    fun keyUp(scancode: Int, extended: Boolean)

    fun lastError(): String

    fun pointerButton(button: MouseButton, pressed: Boolean)

    fun pointerMove(x: UShort, y: UShort)

    fun pointerScroll(horizontal: Short, vertical: Short)

    fun state(): SessionState

    fun surfaceSize(): SurfaceSize

    fun takeFrame(): FrameUpdate?

    fun typeUnicode(code: UInt)

    companion object
}

open class RdpSession: Disposable, AutoCloseable, RdpSessionInterface
{

    /**
     * @suppress
     */
    constructor(handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    constructor() {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_ironrdp_bridge_fn_free_rdpsession(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object")
        }
        return uniffiRustCall { status ->
            UniffiLib.uniffi_ironrdp_bridge_fn_clone_rdpsession(handle, status)
        }
    }

    override fun diagnose(): String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_diagnose(
        it,
        _status)
}
    }
    )
    }


    override fun disconnect()
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_disconnect(
        it,
        _status)
}
    }


    override fun frameCount(): ULong {
            return FfiConverterULong.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_frame_count(
        it,
        _status)
}
    }
    )
    }


    override fun keyDown(scancode: Int, extended: Boolean)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_key_down(
        it,

        FfiConverterInt.lower(scancode),
        FfiConverterBoolean.lower(extended),_status)
}
    }


    override fun keyUp(scancode: Int, extended: Boolean)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_key_up(
        it,

        FfiConverterInt.lower(scancode),
        FfiConverterBoolean.lower(extended),_status)
}
    }


    override fun lastError(): String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_last_error(
        it,
        _status)
}
    }
    )
    }


    override fun pointerButton(button: MouseButton, pressed: Boolean)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_button(
        it,

        FfiConverterTypeMouseButton.lower(button),
        FfiConverterBoolean.lower(pressed),_status)
}
    }


    override fun pointerMove(x: UShort, y: UShort)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_move(
        it,

        FfiConverterUShort.lower(x),
        FfiConverterUShort.lower(y),_status)
}
    }


    override fun pointerScroll(horizontal: Short, vertical: Short)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_pointer_scroll(
        it,

        FfiConverterShort.lower(horizontal),
        FfiConverterShort.lower(vertical),_status)
}
    }


    override fun state(): SessionState {
            return FfiConverterTypeSessionState.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_state(
        it,
        _status)
}
    }
    )
    }


    override fun surfaceSize(): SurfaceSize {
            return FfiConverterTypeSurfaceSize.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_surface_size(
        it,
        _status)
}
    }
    )
    }


    override fun takeFrame(): FrameUpdate? {
            return FfiConverterOptionalTypeFrameUpdate.lift(
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_take_frame(
        it,
        _status)
}
    }
    )
    }


    override fun typeUnicode(code: UInt)
        =
    callWithHandle {
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_method_rdpsession_type_unicode(
        it,

        FfiConverterUInt.lower(code),_status)
}
    }


    companion object {
         fun start(options: ConnectOptions): RdpSession {
            return FfiConverterTypeRdpSession.lift(
    uniffiRustCall { _status ->
    UniffiLib.uniffi_ironrdp_bridge_fn_constructor_rdpsession_start(


        FfiConverterTypeConnectOptions.lower(options),_status)
}
    )
    }


    }

}


/**
 * @suppress
 */
object FfiConverterTypeRdpSession: FfiConverter<RdpSession, Long> {
    override fun lower(value: RdpSession): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): RdpSession {
        return RdpSession(value)
    }

    override fun read(buf: ByteBuffer): RdpSession {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: RdpSession) = 8UL

    override fun write(value: RdpSession, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}


data class ConnectOptions (
    var host: String,
    var port: UShort,
    var username: String,
    var password: String,
    var width: UShort,
    var height: UShort

){


    companion object
}

/**
 * @suppress
 */
object FfiConverterTypeConnectOptions: FfiConverterRustBuffer<ConnectOptions> {
    override fun read(buf: ByteBuffer): ConnectOptions {
        return ConnectOptions(
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf)
        )
    }

    override fun allocationSize(value: ConnectOptions) = (
            FfiConverterString.allocationSize(value.host) +
            FfiConverterUShort.allocationSize(value.port) +
            FfiConverterString.allocationSize(value.username) +
            FfiConverterString.allocationSize(value.password) +
            FfiConverterUShort.allocationSize(value.width) +
            FfiConverterUShort.allocationSize(value.height)
    )

    override fun write(value: ConnectOptions, buf: ByteBuffer) {
            FfiConverterString.write(value.host, buf)
            FfiConverterUShort.write(value.port, buf)
            FfiConverterString.write(value.username, buf)
            FfiConverterString.write(value.password, buf)
            FfiConverterUShort.write(value.width, buf)
            FfiConverterUShort.write(value.height, buf)
    }
}


@Suppress("ArrayInDataClass")
data class FrameRegion (
    var x: UShort,
    var y: UShort,
    var width: UShort,
    var height: UShort,
    /**
     * ARGB-Bytes, pro Pixel A,R,G,B, zeilenweise dicht gepackt.
     * Leer bedeutet: die ganze Flaeche neu zeichnen.
     */
    var argb: ByteArray

){


    companion object
}

/**
 * @suppress
 */
object FfiConverterTypeFrameRegion: FfiConverterRustBuffer<FrameRegion> {
    override fun read(buf: ByteBuffer): FrameRegion {
        return FrameRegion(
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterByteArray.read(buf)
        )
    }

    override fun allocationSize(value: FrameRegion) = (
            FfiConverterUShort.allocationSize(value.x) +
            FfiConverterUShort.allocationSize(value.y) +
            FfiConverterUShort.allocationSize(value.width) +
            FfiConverterUShort.allocationSize(value.height) +
            FfiConverterByteArray.allocationSize(value.argb)
    )

    override fun write(value: FrameRegion, buf: ByteBuffer) {
            FfiConverterUShort.write(value.x, buf)
            FfiConverterUShort.write(value.y, buf)
            FfiConverterUShort.write(value.width, buf)
            FfiConverterUShort.write(value.height, buf)
            FfiConverterByteArray.write(value.argb, buf)
    }
}


data class FrameUpdate (
    var width: UShort,
    var height: UShort,
    var regions: List<FrameRegion>

){


    companion object
}

/**
 * @suppress
 */
object FfiConverterTypeFrameUpdate: FfiConverterRustBuffer<FrameUpdate> {
    override fun read(buf: ByteBuffer): FrameUpdate {
        return FrameUpdate(
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterSequenceTypeFrameRegion.read(buf)
        )
    }

    override fun allocationSize(value: FrameUpdate) = (
            FfiConverterUShort.allocationSize(value.width) +
            FfiConverterUShort.allocationSize(value.height) +
            FfiConverterSequenceTypeFrameRegion.allocationSize(value.regions)
    )

    override fun write(value: FrameUpdate, buf: ByteBuffer) {
            FfiConverterUShort.write(value.width, buf)
            FfiConverterUShort.write(value.height, buf)
            FfiConverterSequenceTypeFrameRegion.write(value.regions, buf)
    }
}


data class SurfaceSize (
    var width: UShort,
    var height: UShort

){


    companion object
}

/**
 * @suppress
 */
object FfiConverterTypeSurfaceSize: FfiConverterRustBuffer<SurfaceSize> {
    override fun read(buf: ByteBuffer): SurfaceSize {
        return SurfaceSize(
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf)
        )
    }

    override fun allocationSize(value: SurfaceSize) = (
            FfiConverterUShort.allocationSize(value.width) +
            FfiConverterUShort.allocationSize(value.height)
    )

    override fun write(value: SurfaceSize, buf: ByteBuffer) {
            FfiConverterUShort.write(value.width, buf)
            FfiConverterUShort.write(value.height, buf)
    }
}


enum class MouseButton {

    LEFT,
    RIGHT,
    MIDDLE;


    companion object
}


/**
 * @suppress
 */
object FfiConverterTypeMouseButton: FfiConverterRustBuffer<MouseButton> {
    override fun read(buf: ByteBuffer) = try {
        MouseButton.entries[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MouseButton) = 4UL

    override fun write(value: MouseButton, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}


enum class SessionState {

    CONNECTING,
    CONNECTED,
    DISCONNECTED,
    FAILED;


    companion object
}


/**
 * @suppress
 */
object FfiConverterTypeSessionState: FfiConverterRustBuffer<SessionState> {
    override fun read(buf: ByteBuffer) = try {
        SessionState.entries[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: SessionState) = 4UL

    override fun write(value: SessionState, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}


/**
 * @suppress
 */
object FfiConverterOptionalTypeFrameUpdate: FfiConverterRustBuffer<FrameUpdate?> {
    override fun read(buf: ByteBuffer): FrameUpdate? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFrameUpdate.read(buf)
    }

    override fun allocationSize(value: FrameUpdate?): ULong {
        if (value == null) {
            return 1UL
        }
        return 1UL + FfiConverterTypeFrameUpdate.allocationSize(value)
    }

    override fun write(value: FrameUpdate?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFrameUpdate.write(value, buf)
        }
    }
}


/**
 * @suppress
 */
object FfiConverterSequenceTypeFrameRegion: FfiConverterRustBuffer<List<FrameRegion>> {
    override fun read(buf: ByteBuffer): List<FrameRegion> {
        val len = buf.getInt()
        return List(len) {
            FfiConverterTypeFrameRegion.read(buf)
        }
    }

    override fun allocationSize(value: List<FrameRegion>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.sumOf { FfiConverterTypeFrameRegion.allocationSize(it) }
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FrameRegion>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeFrameRegion.write(it, buf)
        }
    }
}
